"""Add created_at to tasks

Revision ID: 26fdbcc1e58e
Revises: 0a1243ea28ef
Create Date: 2025-06-04 19:53:58.879680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from datetime import datetime

# revision identifiers, used by Alembic.
revision: str = '26fdbcc1e58e'
down_revision: Union[str, None] = '0a1243ea28ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###

    # 2. Actualiza filas existentes con la fecha actual
    now = datetime.utcnow()
    op.execute(
        f"UPDATE tasks SET created_at = '{now.isoformat(sep=' ', timespec='seconds')}' WHERE created_at IS NULL"
    )

    # 3. Cambia la columna a NOT NULL
    op.alter_column('tasks', 'created_at', nullable=False)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'created_at')
    # ### end Alembic commands ###
